#!/usr/bin/env python2
# coding:utf-8

gitorig = 'gitorig'

import os
import sys

if len(sys.argv) >= 2:
	if sys.argv[1] in ['clone', 'fetch', 'pull']:
		sys.exit(os.system(gitorig + ' ' + sys.argv[1] + ' --depth=1 ' + ' '.join(sys.argv[2:])))

sys.exit(os.system(gitorig + ' ' + ' '.join(sys.argv[1:])))
